### ISSUE TITLE
Please explain " this.published?..... " in "Template.posts.helpers()"?

### ISSUE THREAD

**Issue by thearabbit** [SachaG/smartquery-demo#2]
``` js
Template.posts.helpers({
        // the posts cursor
        posts: function () {
            var limit = Template.instance().limit.get();
            var cursor = Posts.find({}, {limit: limit});
            return SmartQuery.create("posts", cursor);
        },
        postClass: function () {
            return this.published ? "published" : "not-published";
            // What does it mean
        }
    });
```

**Comment by SachaG** [comment]
It's just an arbitrary custom property on the post document I used for the example. Sorry if it's not clear, it's not part of the package or Meteor.

**Comment by thearabbit** [comment]
I don't understand why it can get `published doc` on `Post.

**Comment by SachaG** [comment]
Sorry I don't understand your question? `published` is just a property of a post document.

**Comment by thearabbit** [comment]
yes `published` is just a property of a `post document`.
but I don't understand why we can use `this.` to get it.

**Comment by SachaG** [comment]
Oh, in this case `this` just references the data context, since we're inside an [each](https://github.com/SachaG/smartquery-demo/blob/master/main.html#L23-L29).

**Comment by thearabbit** [comment]
Ow, I miss this.
Thanks again :+1:
